# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:51:12+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class ActivateBasePlanRequest(BaseModel):
    pass


class ActivateSubscriptionOfferRequest(BaseModel):
    pass


class ApkBinary(BaseModel):
    sha1: Optional[str] = Field(
        None,
        description='A sha1 hash of the APK payload, encoded as a hex string and matching the output of the sha1sum command.',
    )
    sha256: Optional[str] = Field(
        None,
        description='A sha256 hash of the APK payload, encoded as a hex string and matching the output of the sha256sum command.',
    )


class AppDetails(BaseModel):
    contactEmail: Optional[str] = Field(
        None, description='The user-visible support email for this app.'
    )
    contactPhone: Optional[str] = Field(
        None, description='The user-visible support telephone number for this app.'
    )
    contactWebsite: Optional[str] = Field(
        None, description='The user-visible website for this app.'
    )
    defaultLanguage: Optional[str] = Field(
        None, description='Default language code, in BCP 47 format (eg "en-US").'
    )


class AppEdit(BaseModel):
    expiryTimeSeconds: Optional[str] = Field(
        None,
        description='Output only. The time (as seconds since Epoch) at which the edit will expire and will be no longer valid for use.',
    )
    id: Optional[str] = Field(
        None,
        description='Output only. Identifier of the edit. Can be used in subsequent API calls.',
    )


class ArchiveSubscriptionRequest(BaseModel):
    pass


class ProrationMode(Enum):
    SUBSCRIPTION_PRORATION_MODE_UNSPECIFIED = 'SUBSCRIPTION_PRORATION_MODE_UNSPECIFIED'
    SUBSCRIPTION_PRORATION_MODE_CHARGE_ON_NEXT_BILLING_DATE = (
        'SUBSCRIPTION_PRORATION_MODE_CHARGE_ON_NEXT_BILLING_DATE'
    )
    SUBSCRIPTION_PRORATION_MODE_CHARGE_FULL_PRICE_IMMEDIATELY = (
        'SUBSCRIPTION_PRORATION_MODE_CHARGE_FULL_PRICE_IMMEDIATELY'
    )


class ResubscribeState(Enum):
    RESUBSCRIBE_STATE_UNSPECIFIED = 'RESUBSCRIBE_STATE_UNSPECIFIED'
    RESUBSCRIBE_STATE_ACTIVE = 'RESUBSCRIBE_STATE_ACTIVE'
    RESUBSCRIBE_STATE_INACTIVE = 'RESUBSCRIBE_STATE_INACTIVE'


class AutoRenewingBasePlanType(BaseModel):
    billingPeriodDuration: Optional[str] = Field(
        None,
        description='Required. Subscription period, specified in ISO 8601 format. For a list of acceptable billing periods, refer to the help center.',
    )
    gracePeriodDuration: Optional[str] = Field(
        None,
        description='Grace period of the subscription, specified in ISO 8601 format. Acceptable values are P0D (zero days), P3D (3 days), P7D (7 days), P14D (14 days), and P30D (30 days). If not specified, a default value will be used based on the recurring period duration.',
    )
    legacyCompatible: Optional[bool] = Field(
        None,
        description='Whether the renewing base plan is backward compatible. The backward compatible base plan is returned by the Google Play Billing Library deprecated method querySkuDetailsAsync(). Only one renewing base plan can be marked as legacy compatible for a given subscription.',
    )
    legacyCompatibleSubscriptionOfferId: Optional[str] = Field(
        None,
        description='Subscription offer id which is legacy compatible. The backward compatible subscription offer is returned by the Google Play Billing Library deprecated method querySkuDetailsAsync(). Only one subscription offer can be marked as legacy compatible for a given renewing base plan. To have no Subscription offer as legacy compatible set this field as empty string.',
    )
    prorationMode: Optional[ProrationMode] = Field(
        None,
        description='The proration mode for the base plan determines what happens when a user switches to this plan from another base plan. If unspecified, defaults to CHARGE_ON_NEXT_BILLING_DATE.',
    )
    resubscribeState: Optional[ResubscribeState] = Field(
        None,
        description='Whether users should be able to resubscribe to this base plan in Google Play surfaces. Defaults to RESUBSCRIBE_STATE_ACTIVE if not specified.',
    )


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    DRAFT = 'DRAFT'
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'


class Bundle(BaseModel):
    sha1: Optional[str] = Field(
        None,
        description='A sha1 hash of the upload payload, encoded as a hex string and matching the output of the sha1sum command.',
    )
    sha256: Optional[str] = Field(
        None,
        description='A sha256 hash of the upload payload, encoded as a hex string and matching the output of the sha256sum command.',
    )
    versionCode: Optional[int] = Field(
        None,
        description="The version code of the Android App Bundle, as specified in the Android App Bundle's base module APK manifest file.",
    )


class BundlesListResponse(BaseModel):
    bundles: Optional[List[Bundle]] = Field(None, description='All app bundles.')
    kind: Optional[str] = Field(
        None,
        description='The kind of this response ("androidpublisher#bundlesListResponse").',
    )


class Reason(Enum):
    CANCEL_SURVEY_REASON_UNSPECIFIED = 'CANCEL_SURVEY_REASON_UNSPECIFIED'
    CANCEL_SURVEY_REASON_NOT_ENOUGH_USAGE = 'CANCEL_SURVEY_REASON_NOT_ENOUGH_USAGE'
    CANCEL_SURVEY_REASON_TECHNICAL_ISSUES = 'CANCEL_SURVEY_REASON_TECHNICAL_ISSUES'
    CANCEL_SURVEY_REASON_COST_RELATED = 'CANCEL_SURVEY_REASON_COST_RELATED'
    CANCEL_SURVEY_REASON_FOUND_BETTER_APP = 'CANCEL_SURVEY_REASON_FOUND_BETTER_APP'
    CANCEL_SURVEY_REASON_OTHERS = 'CANCEL_SURVEY_REASON_OTHERS'


class CancelSurveyResult(BaseModel):
    reason: Optional[Reason] = Field(
        None, description='The reason the user selected in the cancel survey.'
    )
    reasonUserInput: Optional[str] = Field(
        None,
        description="Only set for CANCEL_SURVEY_REASON_OTHERS. This is the user's freeform response to the survey.",
    )


class CountryTargeting(BaseModel):
    countries: Optional[List[str]] = Field(
        None,
        description='Countries to target, specified as two letter [CLDR codes](https://unicode.org/cldr/charts/latest/supplemental/territory_containment_un_m_49.html).',
    )
    includeRestOfWorld: Optional[bool] = Field(
        None,
        description='Include "rest of world" as well as explicitly targeted countries.',
    )


class DeactivateBasePlanRequest(BaseModel):
    pass


class DeactivateSubscriptionOfferRequest(BaseModel):
    pass


class SymbolType(Enum):
    deobfuscationFileTypeUnspecified = 'deobfuscationFileTypeUnspecified'
    proguard = 'proguard'
    nativeCode = 'nativeCode'


class DeobfuscationFile(BaseModel):
    symbolType: Optional[SymbolType] = Field(
        None, description='The type of the deobfuscation file.'
    )


class DeobfuscationFilesUploadResponse(BaseModel):
    deobfuscationFile: Optional[DeobfuscationFile] = Field(
        None, description='The uploaded Deobfuscation File configuration.'
    )


class DeveloperInitiatedCancellation(BaseModel):
    pass


class DeviceId(BaseModel):
    buildBrand: Optional[str] = Field(None, description='Value of Build.BRAND.')
    buildDevice: Optional[str] = Field(None, description='Value of Build.DEVICE.')


class DeviceMetadata(BaseModel):
    cpuMake: Optional[str] = Field(None, description='Device CPU make, e.g. "Qualcomm"')
    cpuModel: Optional[str] = Field(
        None, description='Device CPU model, e.g. "MSM8974"'
    )
    deviceClass: Optional[str] = Field(None, description='Device class (e.g. tablet)')
    glEsVersion: Optional[int] = Field(None, description='OpenGL version')
    manufacturer: Optional[str] = Field(
        None, description='Device manufacturer (e.g. Motorola)'
    )
    nativePlatform: Optional[str] = Field(
        None,
        description='Comma separated list of native platforms (e.g. "arm", "arm7")',
    )
    productName: Optional[str] = Field(
        None, description='Device model name (e.g. Droid)'
    )
    ramMb: Optional[int] = Field(
        None, description='Device RAM in Megabytes, e.g. "2048"'
    )
    screenDensityDpi: Optional[int] = Field(None, description='Screen density in DPI')
    screenHeightPx: Optional[int] = Field(None, description='Screen height in pixels')
    screenWidthPx: Optional[int] = Field(None, description='Screen width in pixels')


class DeviceRam(BaseModel):
    maxBytes: Optional[str] = Field(
        None, description='Maximum RAM in bytes (bound excluded).'
    )
    minBytes: Optional[str] = Field(
        None, description='Minimum RAM in bytes (bound included).'
    )


class DeviceSpec(BaseModel):
    screenDensity: Optional[int] = Field(None, description='Screen dpi.')
    supportedAbis: Optional[List[str]] = Field(
        None,
        description='Supported ABI architectures in the order of preference. The values should be the string as reported by the platform, e.g. "armeabi-v7a", "x86_64".',
    )
    supportedLocales: Optional[List[str]] = Field(
        None,
        description='All installed locales represented as BCP-47 strings, e.g. "en-US".',
    )


class DeviceTier(BaseModel):
    deviceGroupNames: Optional[List[str]] = Field(
        None,
        description='Groups of devices included in this tier. These groups must be defined explicitly under device_groups in this configuration.',
    )
    level: Optional[int] = Field(
        None,
        description="The priority level of the tier. Tiers are evaluated in descending order of level: the highest level tier has the highest priority. The highest tier matching a given device is selected for that device. You should use a contiguous range of levels for your tiers in a tier set; tier levels in a tier set must be unique. For instance, if your tier set has 4 tiers (including the global fallback), you should define tiers 1, 2 and 3 in this configuration. Note: tier 0 is implicitly defined as a global fallback and selected for devices that don't match any of the tiers explicitly defined here. You mustn't define level 0 explicitly in this configuration.",
    )


class DeviceTierSet(BaseModel):
    deviceTiers: Optional[List[DeviceTier]] = Field(
        None, description='Device tiers belonging to the set.'
    )


class ExpansionFile(BaseModel):
    fileSize: Optional[str] = Field(
        None,
        description="If set, this field indicates that this APK has an expansion file uploaded to it: this APK does not reference another APK's expansion file. The field's value is the size of the uploaded expansion file in bytes.",
    )
    referencesVersion: Optional[int] = Field(
        None,
        description="If set, this APK's expansion file references another APK's expansion file. The file_size field will not be set.",
    )


class ExpansionFilesUploadResponse(BaseModel):
    expansionFile: Optional[ExpansionFile] = Field(
        None, description='The uploaded expansion file configuration.'
    )


class ExternalAccountIdentifiers(BaseModel):
    externalAccountId: Optional[str] = Field(
        None,
        description='User account identifier in the third-party service. Only present if account linking happened as part of the subscription purchase flow.',
    )
    obfuscatedExternalAccountId: Optional[str] = Field(
        None,
        description="An obfuscated version of the id that is uniquely associated with the user's account in your app. Present for the following purchases: * If account linking happened as part of the subscription purchase flow. * It was specified using https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setobfuscatedaccountid when the purchase was made.",
    )
    obfuscatedExternalProfileId: Optional[str] = Field(
        None,
        description="An obfuscated version of the id that is uniquely associated with the user's profile in your app. Only present if specified using https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setobfuscatedprofileid when the purchase was made.",
    )


class SubscriptionType(Enum):
    SUBSCRIPTION_TYPE_UNSPECIFIED = 'SUBSCRIPTION_TYPE_UNSPECIFIED'
    RECURRING = 'RECURRING'
    PREPAID = 'PREPAID'


class ExternalSubscription(BaseModel):
    subscriptionType: Optional[SubscriptionType] = Field(
        None, description='Required. The type of the external subscription.'
    )


class TransactionState(Enum):
    TRANSACTION_STATE_UNSPECIFIED = 'TRANSACTION_STATE_UNSPECIFIED'
    TRANSACTION_REPORTED = 'TRANSACTION_REPORTED'
    TRANSACTION_CANCELED = 'TRANSACTION_CANCELED'


class ExternalTransactionAddress(BaseModel):
    regionCode: Optional[str] = Field(
        None,
        description='Required. Two letter region code based on ISO-3166-1 Alpha-2 (UN region codes).',
    )


class ExternalTransactionTestPurchase(BaseModel):
    pass


class FullRefund(BaseModel):
    pass


class GeneratedAssetPackSlice(BaseModel):
    downloadId: Optional[str] = Field(
        None,
        description='Download ID, which uniquely identifies the APK to download. Should be supplied to `generatedapks.download` method.',
    )
    moduleName: Optional[str] = Field(
        None, description='Name of the module that this asset slice belongs to.'
    )
    sliceId: Optional[str] = Field(None, description='Asset slice ID.')
    version: Optional[str] = Field(None, description='Asset module version.')


class GeneratedSplitApk(BaseModel):
    downloadId: Optional[str] = Field(
        None,
        description='Download ID, which uniquely identifies the APK to download. Should be supplied to `generatedapks.download` method.',
    )
    moduleName: Optional[str] = Field(
        None, description='Name of the module that this APK belongs to.'
    )
    splitId: Optional[str] = Field(
        None, description='Split ID. Empty for the main split of the base module.'
    )
    variantId: Optional[int] = Field(None, description='ID of the generated variant.')


class GeneratedStandaloneApk(BaseModel):
    downloadId: Optional[str] = Field(
        None,
        description='Download ID, which uniquely identifies the APK to download. Should be supplied to `generatedapks.download` method.',
    )
    variantId: Optional[int] = Field(None, description='ID of the generated variant.')


class GeneratedUniversalApk(BaseModel):
    downloadId: Optional[str] = Field(
        None,
        description='Download ID, which uniquely identifies the APK to download. Should be supplied to `generatedapks.download` method.',
    )


class AppLevelPermission(Enum):
    APP_LEVEL_PERMISSION_UNSPECIFIED = 'APP_LEVEL_PERMISSION_UNSPECIFIED'
    CAN_ACCESS_APP = 'CAN_ACCESS_APP'
    CAN_VIEW_FINANCIAL_DATA = 'CAN_VIEW_FINANCIAL_DATA'
    CAN_MANAGE_PERMISSIONS = 'CAN_MANAGE_PERMISSIONS'
    CAN_REPLY_TO_REVIEWS = 'CAN_REPLY_TO_REVIEWS'
    CAN_MANAGE_PUBLIC_APKS = 'CAN_MANAGE_PUBLIC_APKS'
    CAN_MANAGE_TRACK_APKS = 'CAN_MANAGE_TRACK_APKS'
    CAN_MANAGE_TRACK_USERS = 'CAN_MANAGE_TRACK_USERS'
    CAN_MANAGE_PUBLIC_LISTING = 'CAN_MANAGE_PUBLIC_LISTING'
    CAN_MANAGE_DRAFT_APPS = 'CAN_MANAGE_DRAFT_APPS'
    CAN_MANAGE_ORDERS = 'CAN_MANAGE_ORDERS'
    CAN_MANAGE_APP_CONTENT = 'CAN_MANAGE_APP_CONTENT'


class Grant(BaseModel):
    appLevelPermissions: Optional[List[AppLevelPermission]] = Field(
        None, description='The permissions granted to the user for this app.'
    )
    name: Optional[str] = Field(
        None,
        description='Required. Resource name for this grant, following the pattern "developers/{developer}/users/{email}/grants/{package_name}". If this grant is for a draft app, the app ID will be used in this resource name instead of the package name.',
    )
    packageName: Optional[str] = Field(
        None,
        description='Immutable. The package name of the app. This will be empty for draft apps.',
    )


class Image(BaseModel):
    id: Optional[str] = Field(None, description='A unique id representing this image.')
    sha1: Optional[str] = Field(None, description='A sha1 hash of the image.')
    sha256: Optional[str] = Field(None, description='A sha256 hash of the image.')
    url: Optional[str] = Field(
        None, description='A URL that will serve a preview of the image.'
    )


class ImagesDeleteAllResponse(BaseModel):
    deleted: Optional[List[Image]] = Field(None, description='The deleted images.')


class ImagesListResponse(BaseModel):
    images: Optional[List[Image]] = Field(None, description='All listed Images.')


class ImagesUploadResponse(BaseModel):
    image: Optional[Image] = Field(None, description='The uploaded image.')


class PurchaseType(Enum):
    purchaseTypeUnspecified = 'purchaseTypeUnspecified'
    managedUser = 'managedUser'
    subscription = 'subscription'


class Status(Enum):
    statusUnspecified = 'statusUnspecified'
    active = 'active'
    inactive = 'inactive'


class InAppProductListing(BaseModel):
    benefits: Optional[List[str]] = Field(
        None, description='Localized entitlement benefits for a subscription.'
    )
    description: Optional[str] = Field(
        None, description='Description for the store listing.'
    )
    title: Optional[str] = Field(None, description='Title for the store listing.')


class InternalAppSharingArtifact(BaseModel):
    certificateFingerprint: Optional[str] = Field(
        None,
        description='The sha256 fingerprint of the certificate used to sign the generated artifact.',
    )
    downloadUrl: Optional[str] = Field(
        None,
        description='The download URL generated for the uploaded artifact. Users that are authorized to download can follow the link to the Play Store app to install it.',
    )
    sha256: Optional[str] = Field(
        None,
        description='The sha256 hash of the artifact represented as a lowercase hexadecimal number, matching the output of the sha256sum command.',
    )


class IntroductoryPriceInfo(BaseModel):
    introductoryPriceAmountMicros: Optional[str] = Field(
        None,
        description='Introductory price of the subscription, not including tax. The currency is the same as price_currency_code. Price is expressed in micro-units, where 1,000,000 micro-units represents one unit of the currency. For example, if the subscription price is €1.99, price_amount_micros is 1990000.',
    )
    introductoryPriceCurrencyCode: Optional[str] = Field(
        None,
        description='ISO 4217 currency code for the introductory subscription price. For example, if the price is specified in British pounds sterling, price_currency_code is "GBP".',
    )
    introductoryPriceCycles: Optional[int] = Field(
        None, description='The number of billing period to offer introductory pricing.'
    )
    introductoryPricePeriod: Optional[str] = Field(
        None,
        description='Introductory price period, specified in ISO 8601 format. Common values are (but not limited to) "P1W" (one week), "P1M" (one month), "P3M" (three months), "P6M" (six months), and "P1Y" (one year).',
    )


class Listing(BaseModel):
    fullDescription: Optional[str] = Field(
        None, description='Full description of the app.'
    )
    language: Optional[str] = Field(
        None,
        description='Language localization code (a BCP-47 language tag; for example, "de-AT" for Austrian German).',
    )
    shortDescription: Optional[str] = Field(
        None, description='Short description of the app.'
    )
    title: Optional[str] = Field(None, description='Localized title of the app.')
    video: Optional[str] = Field(
        None, description='URL of a promotional YouTube video for the app.'
    )


class ListingsListResponse(BaseModel):
    kind: Optional[str] = Field(
        None,
        description='The kind of this response ("androidpublisher#listingsListResponse").',
    )
    listings: Optional[List[Listing]] = Field(
        None, description='All localized listings.'
    )


class LocalizedText(BaseModel):
    language: Optional[str] = Field(
        None,
        description='Language localization code (a BCP-47 language tag; for example, "de-AT" for Austrian German).',
    )
    text: Optional[str] = Field(None, description='The text in the given language.')


class EeaWithdrawalRightType(Enum):
    WITHDRAWAL_RIGHT_TYPE_UNSPECIFIED = 'WITHDRAWAL_RIGHT_TYPE_UNSPECIFIED'
    WITHDRAWAL_RIGHT_DIGITAL_CONTENT = 'WITHDRAWAL_RIGHT_DIGITAL_CONTENT'
    WITHDRAWAL_RIGHT_SERVICE = 'WITHDRAWAL_RIGHT_SERVICE'


class MigrateBasePlanPricesResponse(BaseModel):
    pass


class Money(BaseModel):
    currencyCode: Optional[str] = Field(
        None, description='The three-letter currency code defined in ISO 4217.'
    )
    nanos: Optional[int] = Field(
        None,
        description='Number of nano (10^-9) units of the amount. The value must be between -999,999,999 and +999,999,999 inclusive. If `units` is positive, `nanos` must be positive or zero. If `units` is zero, `nanos` can be positive, zero, or negative. If `units` is negative, `nanos` must be negative or zero. For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.',
    )
    units: Optional[str] = Field(
        None,
        description='The whole units of the amount. For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.',
    )


class OfferDetails(BaseModel):
    basePlanId: Optional[str] = Field(
        None, description='The base plan ID. Present for all base plan and offers.'
    )
    offerId: Optional[str] = Field(
        None, description='The offer ID. Only present for discounted offers.'
    )
    offerTags: Optional[List[str]] = Field(
        None,
        description='The latest offer tags associated with the offer. It includes tags inherited from the base plan.',
    )


class OfferTag(BaseModel):
    tag: Optional[str] = Field(
        None,
        description='Must conform with RFC-1034. That is, this string can only contain lower-case letters (a-z), numbers (0-9), and hyphens (-), and be at most 20 characters.',
    )


class OneTimeExternalTransaction(BaseModel):
    externalTransactionToken: Optional[str] = Field(
        None,
        description='Input only. Provided during the call to Create. Retrieved from the client when the alternative billing flow is launched.',
    )


class OtherRegionsBasePlanConfig(BaseModel):
    eurPrice: Optional[Money] = Field(
        None,
        description='Required. Price in EUR to use for any new locations Play may launch in.',
    )
    newSubscriberAvailability: Optional[bool] = Field(
        None,
        description='Whether the base plan is available for new subscribers in any new locations Play may launch in. If not specified, this will default to false.',
    )
    usdPrice: Optional[Money] = Field(
        None,
        description='Required. Price in USD to use for any new locations Play may launch in.',
    )


class OtherRegionsSubscriptionOfferConfig(BaseModel):
    otherRegionsNewSubscriberAvailability: Optional[bool] = Field(
        None,
        description='Whether the subscription offer in any new locations Play may launch in the future. If not specified, this will default to false.',
    )


class OtherRegionsSubscriptionOfferPhasePrices(BaseModel):
    eurPrice: Optional[Money] = Field(
        None,
        description='Required. Price in EUR to use for any new locations Play may launch in.',
    )
    usdPrice: Optional[Money] = Field(
        None,
        description='Required. Price in USD to use for any new locations Play may launch in.',
    )


class PageInfo(BaseModel):
    resultPerPage: Optional[int] = Field(
        None,
        description='Maximum number of results returned in one page. ! The number of results included in the API response.',
    )
    startIndex: Optional[int] = Field(
        None, description='Index of the first result returned in the current page.'
    )
    totalResults: Optional[int] = Field(
        None,
        description='Total number of results available on the backend ! The total number of results in the result set.',
    )


class PausedStateContext(BaseModel):
    autoResumeTime: Optional[str] = Field(
        None,
        description='Time at which the subscription will be automatically resumed.',
    )


class TimeExtension(Enum):
    TIME_EXTENSION_UNSPECIFIED = 'TIME_EXTENSION_UNSPECIFIED'
    TIME_EXTENSION_ACTIVE = 'TIME_EXTENSION_ACTIVE'
    TIME_EXTENSION_INACTIVE = 'TIME_EXTENSION_INACTIVE'


class PrepaidBasePlanType(BaseModel):
    billingPeriodDuration: Optional[str] = Field(
        None,
        description='Required. Subscription period, specified in ISO 8601 format. For a list of acceptable billing periods, refer to the help center.',
    )
    timeExtension: Optional[TimeExtension] = Field(
        None,
        description='Whether users should be able to extend this prepaid base plan in Google Play surfaces. Defaults to TIME_EXTENSION_ACTIVE if not specified.',
    )


class PrepaidPlan(BaseModel):
    allowExtendAfterTime: Optional[str] = Field(
        None,
        description='If present, this is the time after which top up purchases are allowed for the prepaid plan. Will not be present for expired prepaid plans.',
    )


class Price(BaseModel):
    currency: Optional[str] = Field(
        None,
        description='3 letter Currency code, as defined by ISO 4217. See java/com/google/common/money/CurrencyCode.java',
    )
    priceMicros: Optional[str] = Field(
        None,
        description='Price in 1/million of the currency base unit, represented as a string.',
    )


class ProductPurchase(BaseModel):
    acknowledgementState: Optional[int] = Field(
        None,
        description='The acknowledgement state of the inapp product. Possible values are: 0. Yet to be acknowledged 1. Acknowledged',
    )
    consumptionState: Optional[int] = Field(
        None,
        description='The consumption state of the inapp product. Possible values are: 0. Yet to be consumed 1. Consumed',
    )
    developerPayload: Optional[str] = Field(
        None,
        description='A developer-specified string that contains supplemental information about an order.',
    )
    kind: Optional[str] = Field(
        None,
        description='This kind represents an inappPurchase object in the androidpublisher service.',
    )
    obfuscatedExternalAccountId: Optional[str] = Field(
        None,
        description="An obfuscated version of the id that is uniquely associated with the user's account in your app. Only present if specified using https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setobfuscatedaccountid when the purchase was made.",
    )
    obfuscatedExternalProfileId: Optional[str] = Field(
        None,
        description="An obfuscated version of the id that is uniquely associated with the user's profile in your app. Only present if specified using https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setobfuscatedprofileid when the purchase was made.",
    )
    orderId: Optional[str] = Field(
        None,
        description='The order id associated with the purchase of the inapp product.',
    )
    productId: Optional[str] = Field(
        None, description='The inapp product SKU. May not be present.'
    )
    purchaseState: Optional[int] = Field(
        None,
        description='The purchase state of the order. Possible values are: 0. Purchased 1. Canceled 2. Pending',
    )
    purchaseTimeMillis: Optional[str] = Field(
        None,
        description='The time the product was purchased, in milliseconds since the epoch (Jan 1, 1970).',
    )
    purchaseToken: Optional[str] = Field(
        None,
        description='The purchase token generated to identify this purchase. May not be present.',
    )
    purchaseType: Optional[int] = Field(
        None,
        description='The type of purchase of the inapp product. This field is only set if this purchase was not made using the standard in-app billing flow. Possible values are: 0. Test (i.e. purchased from a license testing account) 1. Promo (i.e. purchased using a promo code) 2. Rewarded (i.e. from watching a video ad instead of paying)',
    )
    quantity: Optional[int] = Field(
        None,
        description='The quantity associated with the purchase of the inapp product. If not present, the quantity is 1.',
    )
    regionCode: Optional[str] = Field(
        None,
        description='ISO 3166-1 alpha-2 billing region code of the user at the time the product was granted.',
    )


class ProductPurchasesAcknowledgeRequest(BaseModel):
    developerPayload: Optional[str] = Field(
        None, description='Payload to attach to the purchase.'
    )


class RecurringExternalTransaction(BaseModel):
    externalSubscription: Optional[ExternalSubscription] = Field(
        None, description='Details of an external subscription.'
    )
    externalTransactionToken: Optional[str] = Field(
        None,
        description='Input only. Provided during the call to Create. Retrieved from the client when the alternative billing flow is launched. Required only for the initial purchase.',
    )
    initialExternalTransactionId: Optional[str] = Field(
        None,
        description='The external transaction id of the first transaction of this recurring series of transactions. For example, for a subscription this would be the transaction id of the first payment. Required when creating recurring external transactions.',
    )


class RegionalBasePlanConfig(BaseModel):
    newSubscriberAvailability: Optional[bool] = Field(
        None,
        description='Whether the base plan in the specified region is available for new subscribers. Existing subscribers will not have their subscription canceled if this value is set to false. If not specified, this will default to false.',
    )
    price: Optional[Money] = Field(
        None,
        description='The price of the base plan in the specified region. Must be set if the base plan is available to new subscribers. Must be set in the currency that is linked to the specified region.',
    )
    regionCode: Optional[str] = Field(
        None,
        description='Required. Region code this configuration applies to, as defined by ISO 3166-2, e.g. "US".',
    )


class RegionalPriceMigrationConfig(BaseModel):
    oldestAllowedPriceVersionTime: Optional[str] = Field(
        None,
        description='Required. The cutoff time for historical prices that subscribers can remain paying. Subscribers who are on a price that was created before this cutoff time will be migrated to the currently-offered price. These subscribers will receive a notification that they will be paying a different price. Subscribers who do not agree to the new price will have their subscription ended at the next renewal.',
    )
    regionCode: Optional[str] = Field(
        None,
        description='Required. Region code this configuration applies to, as defined by ISO 3166-2, e.g. "US".',
    )


class RegionalSubscriptionOfferConfig(BaseModel):
    newSubscriberAvailability: Optional[bool] = Field(
        None,
        description='Whether the subscription offer in the specified region is available for new subscribers. Existing subscribers will not have their subscription cancelled if this value is set to false. If not specified, this will default to false.',
    )
    regionCode: Optional[str] = Field(
        None,
        description='Required. Immutable. Region code this configuration applies to, as defined by ISO 3166-2, e.g. "US".',
    )


class RegionalSubscriptionOfferPhaseConfig(BaseModel):
    absoluteDiscount: Optional[Money] = Field(
        None,
        description='The absolute amount of money subtracted from the base plan price prorated over the phase duration that the user pays for this offer phase. For example, if the base plan price for this region is $12 for a period of 1 year, then a $1 absolute discount for a phase of a duration of 3 months would correspond to a price of $2. The resulting price may not be smaller than the minimum price allowed for this region.',
    )
    price: Optional[Money] = Field(
        None,
        description='The absolute price the user pays for this offer phase. The price must not be smaller than the minimum price allowed for this region.',
    )
    regionCode: Optional[str] = Field(
        None,
        description='Required. Immutable. The region to which this config applies.',
    )
    relativeDiscount: Optional[float] = Field(
        None,
        description='The fraction of the base plan price prorated over the phase duration that the user pays for this offer phase. For example, if the base plan price for this region is $12 for a period of 1 year, then a 50% discount for a phase of a duration of 3 months would correspond to a price of $1.50. The discount must be specified as a fraction strictly larger than 0 and strictly smaller than 1. The resulting price will be rounded to the nearest billable unit (e.g. cents for USD). The relative discount is considered invalid if the discounted price ends up being smaller than the minimum price allowed in this region.',
    )


class StreamingTaxType(Enum):
    STREAMING_TAX_TYPE_UNSPECIFIED = 'STREAMING_TAX_TYPE_UNSPECIFIED'
    STREAMING_TAX_TYPE_TELCO_VIDEO_RENTAL = 'STREAMING_TAX_TYPE_TELCO_VIDEO_RENTAL'
    STREAMING_TAX_TYPE_TELCO_VIDEO_SALES = 'STREAMING_TAX_TYPE_TELCO_VIDEO_SALES'
    STREAMING_TAX_TYPE_TELCO_VIDEO_MULTI_CHANNEL = (
        'STREAMING_TAX_TYPE_TELCO_VIDEO_MULTI_CHANNEL'
    )
    STREAMING_TAX_TYPE_TELCO_AUDIO_RENTAL = 'STREAMING_TAX_TYPE_TELCO_AUDIO_RENTAL'
    STREAMING_TAX_TYPE_TELCO_AUDIO_SALES = 'STREAMING_TAX_TYPE_TELCO_AUDIO_SALES'
    STREAMING_TAX_TYPE_TELCO_AUDIO_MULTI_CHANNEL = (
        'STREAMING_TAX_TYPE_TELCO_AUDIO_MULTI_CHANNEL'
    )


class TaxTier(Enum):
    TAX_TIER_UNSPECIFIED = 'TAX_TIER_UNSPECIFIED'
    TAX_TIER_BOOKS_1 = 'TAX_TIER_BOOKS_1'
    TAX_TIER_NEWS_1 = 'TAX_TIER_NEWS_1'
    TAX_TIER_NEWS_2 = 'TAX_TIER_NEWS_2'
    TAX_TIER_MUSIC_OR_AUDIO_1 = 'TAX_TIER_MUSIC_OR_AUDIO_1'
    TAX_TIER_LIVE_OR_BROADCAST_1 = 'TAX_TIER_LIVE_OR_BROADCAST_1'


class RegionalTaxRateInfo(BaseModel):
    eligibleForStreamingServiceTaxRate: Optional[bool] = Field(
        None,
        description='You must tell us if your app contains streaming products to correctly charge US state and local sales tax. Field only supported in United States.',
    )
    streamingTaxType: Optional[StreamingTaxType] = Field(
        None,
        description='To collect communications or amusement taxes in the United States, choose the appropriate tax category. [Learn more](https://support.google.com/googleplay/android-developer/answer/10463498#streaming_tax).',
    )
    taxTier: Optional[TaxTier] = Field(
        None,
        description='Tax tier to specify reduced tax rate. Developers who sell digital news, magazines, newspapers, books, or audiobooks in various regions may be eligible for reduced tax rates. [Learn more](https://support.google.com/googleplay/android-developer/answer/10463498).',
    )


class RegionsVersion(BaseModel):
    version: Optional[str] = Field(
        None,
        description='Required. A string representing version of the available regions being used for the specified resource. The current version is 2022/02.',
    )


class ReplacementCancellation(BaseModel):
    pass


class ReviewsReplyRequest(BaseModel):
    replyText: Optional[str] = Field(
        None,
        description='The text to set as the reply. Replies of more than approximately 350 characters will be rejected. HTML tags will be stripped.',
    )


class SubscribeWithGoogleInfo(BaseModel):
    emailAddress: Optional[str] = Field(
        None,
        description='The email address of the user when the subscription was purchased.',
    )
    familyName: Optional[str] = Field(
        None,
        description='The family name of the user when the subscription was purchased.',
    )
    givenName: Optional[str] = Field(
        None,
        description='The given name of the user when the subscription was purchased.',
    )
    profileId: Optional[str] = Field(
        None,
        description='The Google profile id of the user when the subscription was purchased.',
    )
    profileName: Optional[str] = Field(
        None,
        description='The profile name of the user when the subscription was purchased.',
    )


class SubscriptionCancelSurveyResult(BaseModel):
    cancelSurveyReason: Optional[int] = Field(
        None,
        description="The cancellation reason the user chose in the survey. Possible values are: 0. Other 1. I don't use this service enough 2. Technical issues 3. Cost-related reasons 4. I found a better app",
    )
    userInputCancelReason: Optional[str] = Field(
        None,
        description='The customized input cancel reason from the user. Only present when cancelReason is 0.',
    )


class SubscriptionDeferralInfo(BaseModel):
    desiredExpiryTimeMillis: Optional[str] = Field(
        None,
        description='The desired next expiry time to assign to the subscription, in milliseconds since the Epoch. The given time must be later/greater than the current expiry time for the subscription.',
    )
    expectedExpiryTimeMillis: Optional[str] = Field(
        None,
        description='The expected expiry time for the subscription. If the current expiry time for the subscription is not the value specified here, the deferral will not occur.',
    )


class PriceChangeMode(Enum):
    PRICE_CHANGE_MODE_UNSPECIFIED = 'PRICE_CHANGE_MODE_UNSPECIFIED'
    PRICE_DECREASE = 'PRICE_DECREASE'
    PRICE_INCREASE = 'PRICE_INCREASE'


class PriceChangeState(Enum):
    PRICE_CHANGE_STATE_UNSPECIFIED = 'PRICE_CHANGE_STATE_UNSPECIFIED'
    OUTSTANDING = 'OUTSTANDING'
    CONFIRMED = 'CONFIRMED'
    APPLIED = 'APPLIED'


class SubscriptionItemPriceChangeDetails(BaseModel):
    expectedNewPriceChargeTime: Optional[str] = Field(
        None,
        description='The renewal time at which the price change will become effective for the user. This is subject to change(to a future time) due to cases where the renewal time shifts like pause.',
    )
    newPrice: Optional[Money] = Field(
        None, description='New recurring price for the subscription item.'
    )
    priceChangeMode: Optional[PriceChangeMode] = Field(
        None,
        description='Price change mode specifies how the subscription item price is changing.',
    )
    priceChangeState: Optional[PriceChangeState] = Field(
        None, description='State the price change is currently in.'
    )


class SubscriptionListing(BaseModel):
    benefits: Optional[List[str]] = Field(
        None,
        description='A list of benefits shown to the user on platforms such as the Play Store and in restoration flows in the language of this listing. Plain text. Ordered list of at most four benefits.',
    )
    description: Optional[str] = Field(
        None,
        description='The description of this subscription in the language of this listing. Maximum length - 80 characters. Plain text.',
    )
    languageCode: Optional[str] = Field(
        None,
        description='Required. The language of this listing, as defined by BCP-47, e.g. "en-US".',
    )
    title: Optional[str] = Field(
        None,
        description='Required. The title of this subscription in the language of this listing. Plain text.',
    )


class SubscriptionPriceChange(BaseModel):
    newPrice: Optional[Price] = Field(
        None,
        description='The new price the subscription will renew with if the price change is accepted by the user.',
    )
    state: Optional[int] = Field(
        None,
        description="The current state of the price change. Possible values are: 0. Outstanding: State for a pending price change waiting for the user to agree. In this state, you can optionally seek confirmation from the user using the In-App API. 1. Accepted: State for an accepted price change that the subscription will renew with unless it's canceled. The price change takes effect on a future date when the subscription renews. Note that the change might not occur when the subscription is renewed next.",
    )


class SubscriptionPurchase(BaseModel):
    acknowledgementState: Optional[int] = Field(
        None,
        description='The acknowledgement state of the subscription product. Possible values are: 0. Yet to be acknowledged 1. Acknowledged',
    )
    autoRenewing: Optional[bool] = Field(
        None,
        description='Whether the subscription will automatically be renewed when it reaches its current expiry time.',
    )
    autoResumeTimeMillis: Optional[str] = Field(
        None,
        description='Time at which the subscription will be automatically resumed, in milliseconds since the Epoch. Only present if the user has requested to pause the subscription.',
    )
    cancelReason: Optional[int] = Field(
        None,
        description='The reason why a subscription was canceled or is not auto-renewing. Possible values are: 0. User canceled the subscription 1. Subscription was canceled by the system, for example because of a billing problem 2. Subscription was replaced with a new subscription 3. Subscription was canceled by the developer',
    )
    cancelSurveyResult: Optional[SubscriptionCancelSurveyResult] = Field(
        None,
        description='Information provided by the user when they complete the subscription cancellation flow (cancellation reason survey).',
    )
    countryCode: Optional[str] = Field(
        None,
        description='ISO 3166-1 alpha-2 billing country/region code of the user at the time the subscription was granted.',
    )
    developerPayload: Optional[str] = Field(
        None,
        description='A developer-specified string that contains supplemental information about an order.',
    )
    emailAddress: Optional[str] = Field(
        None,
        description="The email address of the user when the subscription was purchased. Only present for purchases made with 'Subscribe with Google'.",
    )
    expiryTimeMillis: Optional[str] = Field(
        None,
        description='Time at which the subscription will expire, in milliseconds since the Epoch.',
    )
    externalAccountId: Optional[str] = Field(
        None,
        description='User account identifier in the third-party service. Only present if account linking happened as part of the subscription purchase flow.',
    )
    familyName: Optional[str] = Field(
        None,
        description="The family name of the user when the subscription was purchased. Only present for purchases made with 'Subscribe with Google'.",
    )
    givenName: Optional[str] = Field(
        None,
        description="The given name of the user when the subscription was purchased. Only present for purchases made with 'Subscribe with Google'.",
    )
    introductoryPriceInfo: Optional[IntroductoryPriceInfo] = Field(
        None,
        description='Introductory price information of the subscription. This is only present when the subscription was purchased with an introductory price. This field does not indicate the subscription is currently in introductory price period.',
    )
    kind: Optional[str] = Field(
        None,
        description='This kind represents a subscriptionPurchase object in the androidpublisher service.',
    )
    linkedPurchaseToken: Optional[str] = Field(
        None,
        description='The purchase token of the originating purchase if this subscription is one of the following: 0. Re-signup of a canceled but non-lapsed subscription 1. Upgrade/downgrade from a previous subscription For example, suppose a user originally signs up and you receive purchase token X, then the user cancels and goes through the resignup flow (before their subscription lapses) and you receive purchase token Y, and finally the user upgrades their subscription and you receive purchase token Z. If you call this API with purchase token Z, this field will be set to Y. If you call this API with purchase token Y, this field will be set to X. If you call this API with purchase token X, this field will not be set.',
    )
    obfuscatedExternalAccountId: Optional[str] = Field(
        None,
        description="An obfuscated version of the id that is uniquely associated with the user's account in your app. Present for the following purchases: * If account linking happened as part of the subscription purchase flow. * It was specified using https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setobfuscatedaccountid when the purchase was made.",
    )
    obfuscatedExternalProfileId: Optional[str] = Field(
        None,
        description="An obfuscated version of the id that is uniquely associated with the user's profile in your app. Only present if specified using https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setobfuscatedprofileid when the purchase was made.",
    )
    orderId: Optional[str] = Field(
        None,
        description='The order id of the latest recurring order associated with the purchase of the subscription. If the subscription was canceled because payment was declined, this will be the order id from the payment declined order.',
    )
    paymentState: Optional[int] = Field(
        None,
        description='The payment state of the subscription. Possible values are: 0. Payment pending 1. Payment received 2. Free trial 3. Pending deferred upgrade/downgrade Not present for canceled, expired subscriptions.',
    )
    priceAmountMicros: Optional[str] = Field(
        None,
        description="Price of the subscription, For tax exclusive countries, the price doesn't include tax. For tax inclusive countries, the price includes tax. Price is expressed in micro-units, where 1,000,000 micro-units represents one unit of the currency. For example, if the subscription price is €1.99, price_amount_micros is 1990000.",
    )
    priceChange: Optional[SubscriptionPriceChange] = Field(
        None,
        description='The latest price change information available. This is present only when there is an upcoming price change for the subscription yet to be applied. Once the subscription renews with the new price or the subscription is canceled, no price change information will be returned.',
    )
    priceCurrencyCode: Optional[str] = Field(
        None,
        description='ISO 4217 currency code for the subscription price. For example, if the price is specified in British pounds sterling, price_currency_code is "GBP".',
    )
    profileId: Optional[str] = Field(
        None,
        description="The Google profile id of the user when the subscription was purchased. Only present for purchases made with 'Subscribe with Google'.",
    )
    profileName: Optional[str] = Field(
        None,
        description="The profile name of the user when the subscription was purchased. Only present for purchases made with 'Subscribe with Google'.",
    )
    promotionCode: Optional[str] = Field(
        None,
        description='The promotion code applied on this purchase. This field is only set if a vanity code promotion is applied when the subscription was purchased.',
    )
    promotionType: Optional[int] = Field(
        None,
        description='The type of promotion applied on this purchase. This field is only set if a promotion is applied when the subscription was purchased. Possible values are: 0. One time code 1. Vanity code',
    )
    purchaseType: Optional[int] = Field(
        None,
        description='The type of purchase of the subscription. This field is only set if this purchase was not made using the standard in-app billing flow. Possible values are: 0. Test (i.e. purchased from a license testing account) 1. Promo (i.e. purchased using a promo code)',
    )
    startTimeMillis: Optional[str] = Field(
        None,
        description='Time at which the subscription was granted, in milliseconds since the Epoch.',
    )
    userCancellationTimeMillis: Optional[str] = Field(
        None,
        description='The time at which the subscription was canceled by the user, in milliseconds since the epoch. Only present if cancelReason is 0.',
    )


class AcknowledgementState(Enum):
    ACKNOWLEDGEMENT_STATE_UNSPECIFIED = 'ACKNOWLEDGEMENT_STATE_UNSPECIFIED'
    ACKNOWLEDGEMENT_STATE_PENDING = 'ACKNOWLEDGEMENT_STATE_PENDING'
    ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED = 'ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED'


class SubscriptionState(Enum):
    SUBSCRIPTION_STATE_UNSPECIFIED = 'SUBSCRIPTION_STATE_UNSPECIFIED'
    SUBSCRIPTION_STATE_PENDING = 'SUBSCRIPTION_STATE_PENDING'
    SUBSCRIPTION_STATE_ACTIVE = 'SUBSCRIPTION_STATE_ACTIVE'
    SUBSCRIPTION_STATE_PAUSED = 'SUBSCRIPTION_STATE_PAUSED'
    SUBSCRIPTION_STATE_IN_GRACE_PERIOD = 'SUBSCRIPTION_STATE_IN_GRACE_PERIOD'
    SUBSCRIPTION_STATE_ON_HOLD = 'SUBSCRIPTION_STATE_ON_HOLD'
    SUBSCRIPTION_STATE_CANCELED = 'SUBSCRIPTION_STATE_CANCELED'
    SUBSCRIPTION_STATE_EXPIRED = 'SUBSCRIPTION_STATE_EXPIRED'


class SubscriptionPurchasesAcknowledgeRequest(BaseModel):
    developerPayload: Optional[str] = Field(
        None, description='Payload to attach to the purchase.'
    )


class SubscriptionPurchasesDeferRequest(BaseModel):
    deferralInfo: Optional[SubscriptionDeferralInfo] = Field(
        None,
        description='The information about the new desired expiry time for the subscription.',
    )


class SubscriptionPurchasesDeferResponse(BaseModel):
    newExpiryTimeMillis: Optional[str] = Field(
        None,
        description='The new expiry time for the subscription in milliseconds since the Epoch.',
    )


class SubscriptionTaxAndComplianceSettings(BaseModel):
    eeaWithdrawalRightType: Optional[EeaWithdrawalRightType] = Field(
        None,
        description='Digital content or service classification for products distributed to users in the European Economic Area (EEA). The withdrawal regime under EEA consumer laws depends on this classification. Refer to the [Help Center article](https://support.google.com/googleplay/android-developer/answer/10463498) for more information.',
    )
    taxRateInfoByRegionCode: Optional[Dict[str, RegionalTaxRateInfo]] = Field(
        None,
        description='A mapping from region code to tax rate details. The keys are region codes as defined by Unicode\'s "CLDR".',
    )


class SystemFeature(BaseModel):
    name: Optional[str] = Field(None, description='The name of the feature.')


class SystemInitiatedCancellation(BaseModel):
    pass


class TargetingRuleScope(BaseModel):
    specificSubscriptionInApp: Optional[str] = Field(
        None,
        description='The scope of the current targeting rule is the subscription with the specified subscription ID. Must be a subscription within the same parent app.',
    )


class TestPurchase(BaseModel):
    pass


class Testers(BaseModel):
    googleGroups: Optional[List[str]] = Field(
        None, description='All testing Google Groups, as email addresses.'
    )


class Timestamp(BaseModel):
    nanos: Optional[int] = Field(
        None,
        description='Non-negative fractions of a second at nanosecond resolution. Must be from 0 to 999,999,999 inclusive.',
    )
    seconds: Optional[str] = Field(
        None, description='Represents seconds of UTC time since Unix epoch.'
    )


class TokenPagination(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description="Tokens to pass to the standard list field 'page_token'. Whenever available, tokens are preferred over manipulating start_index.",
    )
    previousPageToken: Optional[str] = None


class Status1(Enum):
    statusUnspecified = 'statusUnspecified'
    draft = 'draft'
    inProgress = 'inProgress'
    halted = 'halted'
    completed = 'completed'


class TrackRelease(BaseModel):
    countryTargeting: Optional[CountryTargeting] = Field(
        None, description='Restricts a release to a specific set of countries.'
    )
    inAppUpdatePriority: Optional[int] = Field(
        None,
        description='In-app update priority of the release. All newly added APKs in the release will be considered at this priority. Can take values in the range [0, 5], with 5 the highest priority. Defaults to 0. in_app_update_priority can not be updated once the release is rolled out. See https://developer.android.com/guide/playcore/in-app-updates.',
    )
    name: Optional[str] = Field(
        None,
        description="The release name. Not required to be unique. If not set, the name is generated from the APK's version_name. If the release contains multiple APKs, the name is generated from the date.",
    )
    releaseNotes: Optional[List[LocalizedText]] = Field(
        None, description='A description of what is new in this release.'
    )
    status: Optional[Status1] = Field(None, description='The status of the release.')
    userFraction: Optional[float] = Field(
        None,
        description='Fraction of users who are eligible for a staged release. 0 < fraction < 1. Can only be set when status is "inProgress" or "halted".',
    )
    versionCodes: Optional[List[str]] = Field(
        None,
        description='Version codes of all APKs in the release. Must include version codes to retain from previous releases.',
    )


class TrackTargetedCountry(BaseModel):
    countryCode: Optional[str] = Field(
        None, description='The country to target, as a two-letter CLDR code.'
    )


class UpgradeTargetingRule(BaseModel):
    billingPeriodDuration: Optional[str] = Field(
        None,
        description='The specific billing period duration, specified in ISO 8601 format, that a user must be currently subscribed to to be eligible for this rule. If not specified, users subscribed to any billing period are matched.',
    )
    oncePerUser: Optional[bool] = Field(
        None,
        description='Limit this offer to only once per user. If set to true, a user can never be eligible for this offer again if they ever subscribed to this offer.',
    )
    scope: Optional[TargetingRuleScope] = Field(
        None,
        description='Required. The scope of subscriptions this rule considers. Only allows "this subscription" and "specific subscription in app".',
    )


class AccessState(Enum):
    ACCESS_STATE_UNSPECIFIED = 'ACCESS_STATE_UNSPECIFIED'
    INVITED = 'INVITED'
    INVITATION_EXPIRED = 'INVITATION_EXPIRED'
    ACCESS_GRANTED = 'ACCESS_GRANTED'
    ACCESS_EXPIRED = 'ACCESS_EXPIRED'


class DeveloperAccountPermission(Enum):
    DEVELOPER_LEVEL_PERMISSION_UNSPECIFIED = 'DEVELOPER_LEVEL_PERMISSION_UNSPECIFIED'
    CAN_SEE_ALL_APPS = 'CAN_SEE_ALL_APPS'
    CAN_VIEW_FINANCIAL_DATA_GLOBAL = 'CAN_VIEW_FINANCIAL_DATA_GLOBAL'
    CAN_MANAGE_PERMISSIONS_GLOBAL = 'CAN_MANAGE_PERMISSIONS_GLOBAL'
    CAN_EDIT_GAMES_GLOBAL = 'CAN_EDIT_GAMES_GLOBAL'
    CAN_PUBLISH_GAMES_GLOBAL = 'CAN_PUBLISH_GAMES_GLOBAL'
    CAN_REPLY_TO_REVIEWS_GLOBAL = 'CAN_REPLY_TO_REVIEWS_GLOBAL'
    CAN_MANAGE_PUBLIC_APKS_GLOBAL = 'CAN_MANAGE_PUBLIC_APKS_GLOBAL'
    CAN_MANAGE_TRACK_APKS_GLOBAL = 'CAN_MANAGE_TRACK_APKS_GLOBAL'
    CAN_MANAGE_TRACK_USERS_GLOBAL = 'CAN_MANAGE_TRACK_USERS_GLOBAL'
    CAN_MANAGE_PUBLIC_LISTING_GLOBAL = 'CAN_MANAGE_PUBLIC_LISTING_GLOBAL'
    CAN_MANAGE_DRAFT_APPS_GLOBAL = 'CAN_MANAGE_DRAFT_APPS_GLOBAL'
    CAN_CREATE_MANAGED_PLAY_APPS_GLOBAL = 'CAN_CREATE_MANAGED_PLAY_APPS_GLOBAL'
    CAN_CHANGE_MANAGED_PLAY_SETTING_GLOBAL = 'CAN_CHANGE_MANAGED_PLAY_SETTING_GLOBAL'
    CAN_MANAGE_ORDERS_GLOBAL = 'CAN_MANAGE_ORDERS_GLOBAL'
    CAN_MANAGE_APP_CONTENT_GLOBAL = 'CAN_MANAGE_APP_CONTENT_GLOBAL'


class User(BaseModel):
    accessState: Optional[AccessState] = Field(
        None,
        description="Output only. The state of the user's access to the Play Console.",
    )
    developerAccountPermissions: Optional[List[DeveloperAccountPermission]] = Field(
        None,
        description='Permissions for the user which apply across the developer account.',
    )
    email: Optional[str] = Field(
        None, description="Immutable. The user's email address."
    )
    expirationTime: Optional[str] = Field(
        None,
        description="The time at which the user's access expires, if set. When setting this value, it must always be in the future.",
    )
    grants: Optional[List[Grant]] = Field(
        None, description='Output only. Per-app permissions for the user.'
    )
    name: Optional[str] = Field(
        None,
        description='Required. Resource name for this user, following the pattern "developers/{developer}/users/{email}".',
    )
    partial: Optional[bool] = Field(
        None,
        description="Output only. Whether there are more permissions for the user that are not represented here. This can happen if the caller does not have permission to manage all apps in the account. This is also `true` if this user is the account owner. If this field is `true`, it should be taken as a signal that this user cannot be fully managed via the API. That is, the API caller is not be able to manage all of the permissions this user holds, either because it doesn't know about them or because the user is the account owner.",
    )


class UserComment(BaseModel):
    androidOsVersion: Optional[int] = Field(
        None,
        description="Integer Android SDK version of the user's device at the time the review was written, e.g. 23 is Marshmallow. May be absent.",
    )
    appVersionCode: Optional[int] = Field(
        None,
        description='Integer version code of the app as installed at the time the review was written. May be absent.',
    )
    appVersionName: Optional[str] = Field(
        None,
        description='String version name of the app as installed at the time the review was written. May be absent.',
    )
    device: Optional[str] = Field(
        None,
        description="Codename for the reviewer's device, e.g. klte, flounder. May be absent.",
    )
    deviceMetadata: Optional[DeviceMetadata] = Field(
        None, description="Information about the characteristics of the user's device."
    )
    lastModified: Optional[Timestamp] = Field(
        None, description='The last time at which this comment was updated.'
    )
    originalText: Optional[str] = Field(
        None,
        description='Untranslated text of the review, where the review was translated. If the review was not translated this is left blank.',
    )
    reviewerLanguage: Optional[str] = Field(
        None,
        description='Language code for the reviewer. This is taken from the device settings so is not guaranteed to match the language the review is written in. May be absent.',
    )
    starRating: Optional[int] = Field(
        None, description='The star rating associated with the review, from 1 to 5.'
    )
    text: Optional[str] = Field(
        None,
        description='The content of the comment, i.e. review body. In some cases users have been able to write a review with separate title and body; in those cases the title and body are concatenated and separated by a tab character.',
    )
    thumbsDownCount: Optional[int] = Field(
        None, description='Number of users who have given this review a thumbs down.'
    )
    thumbsUpCount: Optional[int] = Field(
        None, description='Number of users who have given this review a thumbs up.'
    )


class UserCountrySet(BaseModel):
    countryCodes: Optional[List[str]] = Field(
        None,
        description='List of country codes representing countries. A Country code is represented in ISO 3166 alpha-2 format. For Example:- "IT" for Italy, "GE" for Georgia.',
    )
    name: Optional[str] = Field(None, description='Country set name.')


class UserInitiatedCancellation(BaseModel):
    cancelSurveyResult: Optional[CancelSurveyResult] = Field(
        None,
        description='Information provided by the user when they complete the subscription cancellation flow (cancellation reason survey).',
    )
    cancelTime: Optional[str] = Field(
        None,
        description='The time at which the subscription was canceled by the user. The user might still have access to the subscription after this time. Use line_items.expiry_time to determine if a user still has access.',
    )


class UsesPermission(BaseModel):
    maxSdkVersion: Optional[int] = Field(
        None,
        description='Optionally, the maximum SDK version for which the permission is required.',
    )
    name: Optional[str] = Field(
        None, description='The name of the permission requested.'
    )


class Variant(BaseModel):
    deviceSpec: Optional[DeviceSpec] = Field(
        None, description='The device spec used to generate the APK.'
    )
    variantId: Optional[int] = Field(
        None,
        description='Output only. The ID of a previously created system APK variant.',
    )


class VoidedPurchase(BaseModel):
    kind: Optional[str] = Field(
        None,
        description='This kind represents a voided purchase object in the androidpublisher service.',
    )
    orderId: Optional[str] = Field(
        None,
        description='The order id which uniquely identifies a one-time purchase, subscription purchase, or subscription renewal.',
    )
    purchaseTimeMillis: Optional[str] = Field(
        None,
        description='The time at which the purchase was made, in milliseconds since the epoch (Jan 1, 1970).',
    )
    purchaseToken: Optional[str] = Field(
        None,
        description='The token which uniquely identifies a one-time purchase or subscription. To uniquely identify subscription renewals use order_id (available starting from version 3 of the API).',
    )
    voidedReason: Optional[int] = Field(
        None,
        description='The reason why the purchase was voided, possible values are: 0. Other 1. Remorse 2. Not_received 3. Defective 4. Accidental_purchase 5. Fraud 6. Friendly_fraud 7. Chargeback',
    )
    voidedSource: Optional[int] = Field(
        None,
        description='The initiator of voided purchase, possible values are: 0. User 1. Developer 2. Google',
    )
    voidedTimeMillis: Optional[str] = Field(
        None,
        description='The time at which the purchase was canceled/refunded/charged-back, in milliseconds since the epoch (Jan 1, 1970).',
    )


class VoidedPurchasesListResponse(BaseModel):
    pageInfo: Optional[PageInfo] = Field(
        None, description='General pagination information.'
    )
    tokenPagination: Optional[TokenPagination] = Field(
        None, description='Pagination information for token pagination.'
    )
    voidedPurchases: Optional[List[VoidedPurchase]] = None


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class DeobfuscationFileType(Enum):
    deobfuscationFileTypeUnspecified = 'deobfuscationFileTypeUnspecified'
    proguard = 'proguard'
    nativeCode = 'nativeCode'


class ExpansionFileType(Enum):
    expansionFileTypeUnspecified = 'expansionFileTypeUnspecified'
    main = 'main'
    patch = 'patch'


class ImageType(Enum):
    appImageTypeUnspecified = 'appImageTypeUnspecified'
    phoneScreenshots = 'phoneScreenshots'
    sevenInchScreenshots = 'sevenInchScreenshots'
    tenInchScreenshots = 'tenInchScreenshots'
    tvScreenshots = 'tvScreenshots'
    wearScreenshots = 'wearScreenshots'
    icon = 'icon'
    featureGraphic = 'featureGraphic'
    tvBanner = 'tvBanner'


class AcquisitionTargetingRule(BaseModel):
    scope: Optional[TargetingRuleScope] = Field(
        None,
        description='Required. The scope of subscriptions this rule considers. Only allows "this subscription" and "any subscription in app".',
    )


class Apk(BaseModel):
    binary: Optional[ApkBinary] = Field(
        None, description='Information about the binary payload of this APK.'
    )
    versionCode: Optional[int] = Field(
        None,
        description='The version code of the APK, as specified in the manifest file.',
    )


class ApksListResponse(BaseModel):
    apks: Optional[List[Apk]] = Field(None, description='All APKs.')
    kind: Optional[str] = Field(
        None,
        description='The kind of this response ("androidpublisher#apksListResponse").',
    )


class AutoRenewingPlan(BaseModel):
    autoRenewEnabled: Optional[bool] = Field(
        None,
        description='If the subscription is currently set to auto-renew, e.g. the user has not canceled the subscription',
    )
    priceChangeDetails: Optional[SubscriptionItemPriceChangeDetails] = Field(
        None,
        description='The information of the last price change for the item since subscription signup.',
    )


class BasePlan(BaseModel):
    autoRenewingBasePlanType: Optional[AutoRenewingBasePlanType] = Field(
        None,
        description='Set when the base plan automatically renews at a regular interval.',
    )
    basePlanId: Optional[str] = Field(
        None,
        description='Required. Immutable. The unique identifier of this base plan. Must be unique within the subscription, and conform with RFC-1034. That is, this ID can only contain lower-case letters (a-z), numbers (0-9), and hyphens (-), and be at most 63 characters.',
    )
    offerTags: Optional[List[OfferTag]] = Field(
        None,
        description='List of up to 20 custom tags specified for this base plan, and returned to the app through the billing library. Subscription offers for this base plan will also receive these offer tags in the billing library.',
    )
    otherRegionsConfig: Optional[OtherRegionsBasePlanConfig] = Field(
        None,
        description='Pricing information for any new locations Play may launch in the future. If omitted, the BasePlan will not be automatically available any new locations Play may launch in the future.',
    )
    prepaidBasePlanType: Optional[PrepaidBasePlanType] = Field(
        None,
        description='Set when the base plan does not automatically renew at the end of the billing period.',
    )
    regionalConfigs: Optional[List[RegionalBasePlanConfig]] = Field(
        None, description='Region-specific information for this base plan.'
    )
    state: Optional[State] = Field(
        None,
        description="Output only. The state of the base plan, i.e. whether it's active. Draft and inactive base plans can be activated or deleted. Active base plans can be made inactive. Inactive base plans can be canceled. This field cannot be changed by updating the resource. Use the dedicated endpoints instead.",
    )


class CanceledStateContext(BaseModel):
    developerInitiatedCancellation: Optional[DeveloperInitiatedCancellation] = Field(
        None, description='Subscription was canceled by the developer.'
    )
    replacementCancellation: Optional[ReplacementCancellation] = Field(
        None, description='Subscription was replaced by a new subscription.'
    )
    systemInitiatedCancellation: Optional[SystemInitiatedCancellation] = Field(
        None,
        description='Subscription was canceled by the system, for example because of a billing problem.',
    )
    userInitiatedCancellation: Optional[UserInitiatedCancellation] = Field(
        None, description='Subscription was canceled by user.'
    )


class ConvertRegionPricesRequest(BaseModel):
    price: Optional[Money] = Field(
        None,
        description='The intital price to convert other regions from. Tax exclusive.',
    )


class ConvertedOtherRegionsPrice(BaseModel):
    eurPrice: Optional[Money] = Field(
        None,
        description='Price in EUR to use for the "Other regions" location exclusive of taxes.',
    )
    usdPrice: Optional[Money] = Field(
        None,
        description='Price in USD to use for the "Other regions" location exclusive of taxes.',
    )


class ConvertedRegionPrice(BaseModel):
    price: Optional[Money] = Field(
        None, description='The converted price tax inclusive.'
    )
    regionCode: Optional[str] = Field(
        None, description='The region code of the region.'
    )
    taxAmount: Optional[Money] = Field(
        None, description='The tax amount of the converted price.'
    )


class DeveloperComment(BaseModel):
    lastModified: Optional[Timestamp] = Field(
        None, description='The last time at which this comment was updated.'
    )
    text: Optional[str] = Field(
        None, description='The content of the comment, i.e. reply body.'
    )


class DeviceSelector(BaseModel):
    deviceRam: Optional[DeviceRam] = Field(
        None, description="Conditions on the device's RAM."
    )
    excludedDeviceIds: Optional[List[DeviceId]] = Field(
        None,
        description='Device models excluded by this selector, even if they match all other conditions.',
    )
    forbiddenSystemFeatures: Optional[List[SystemFeature]] = Field(
        None,
        description='A device that has any of these system features is excluded by this selector, even if it matches all other conditions.',
    )
    includedDeviceIds: Optional[List[DeviceId]] = Field(
        None, description='Device models included by this selector.'
    )
    requiredSystemFeatures: Optional[List[SystemFeature]] = Field(
        None,
        description='A device needs to have all these system features to be included by the selector.',
    )


class ExternalTransaction(BaseModel):
    createTime: Optional[str] = Field(
        None,
        description='Output only. The time when this transaction was created. This is the time when Google was notified of the transaction.',
    )
    currentPreTaxAmount: Optional[Price] = Field(
        None,
        description='Output only. The current transaction amount before tax. This represents the current pre-tax amount including any refunds that may have been applied to this transaction.',
    )
    currentTaxAmount: Optional[Price] = Field(
        None,
        description='Output only. The current tax amount. This represents the current tax amount including any refunds that may have been applied to this transaction.',
    )
    externalTransactionId: Optional[str] = Field(
        None,
        description='Output only. The id of this transaction. All transaction ids under the same package name must be unique. Set when creating the external transaction.',
    )
    oneTimeTransaction: Optional[OneTimeExternalTransaction] = Field(
        None,
        description='This is a one-time transaction and not part of a subscription.',
    )
    originalPreTaxAmount: Optional[Price] = Field(
        None,
        description='Required. The original transaction amount before taxes. This represents the pre-tax amount originally notified to Google before any refunds were applied.',
    )
    originalTaxAmount: Optional[Price] = Field(
        None,
        description='Required. The original tax amount. This represents the tax amount originally notified to Google before any refunds were applied.',
    )
    packageName: Optional[str] = Field(
        None,
        description="Output only. The resource name of the external transaction. The package name of the application the inapp products were sold (for example, 'com.some.app').",
    )
    recurringTransaction: Optional[RecurringExternalTransaction] = Field(
        None,
        description='This transaction is part of a recurring series of transactions.',
    )
    testPurchase: Optional[ExternalTransactionTestPurchase] = Field(
        None,
        description='Output only. If set, this transaction was a test purchase. Google will not charge for a test transaction.',
    )
    transactionState: Optional[TransactionState] = Field(
        None, description='Output only. The current state of the transaction.'
    )
    transactionTime: Optional[str] = Field(
        None, description='Required. The time when the transaction was completed.'
    )
    userTaxAddress: Optional[ExternalTransactionAddress] = Field(
        None, description='Required. User address for tax computation.'
    )


class ExternallyHostedApk(BaseModel):
    applicationLabel: Optional[str] = Field(None, description='The application label.')
    certificateBase64s: Optional[List[str]] = Field(
        None,
        description='A certificate (or array of certificates if a certificate-chain is used) used to sign this APK, represented as a base64 encoded byte array.',
    )
    externallyHostedUrl: Optional[str] = Field(
        None,
        description='The URL at which the APK is hosted. This must be an https URL.',
    )
    fileSha1Base64: Optional[str] = Field(
        None,
        description='The sha1 checksum of this APK, represented as a base64 encoded byte array.',
    )
    fileSha256Base64: Optional[str] = Field(
        None,
        description='The sha256 checksum of this APK, represented as a base64 encoded byte array.',
    )
    fileSize: Optional[str] = Field(
        None, description='The file size in bytes of this APK.'
    )
    iconBase64: Optional[str] = Field(
        None, description='The icon image from the APK, as a base64 encoded byte array.'
    )
    maximumSdk: Optional[int] = Field(
        None, description='The maximum SDK supported by this APK (optional).'
    )
    minimumSdk: Optional[int] = Field(
        None, description='The minimum SDK targeted by this APK.'
    )
    nativeCodes: Optional[List[str]] = Field(
        None,
        description='The native code environments supported by this APK (optional).',
    )
    packageName: Optional[str] = Field(None, description='The package name.')
    usesFeatures: Optional[List[str]] = Field(
        None, description='The features required by this APK (optional).'
    )
    usesPermissions: Optional[List[UsesPermission]] = Field(
        None, description='The permissions requested by this APK.'
    )
    versionCode: Optional[int] = Field(
        None, description='The version code of this APK.'
    )
    versionName: Optional[str] = Field(
        None, description='The version name of this APK.'
    )


class GeneratedApksPerSigningKey(BaseModel):
    certificateSha256Hash: Optional[str] = Field(
        None, description='SHA256 hash of the APK signing public key certificate.'
    )
    generatedAssetPackSlices: Optional[List[GeneratedAssetPackSlice]] = Field(
        None,
        description='List of asset pack slices which will be served for this app bundle, signed with a key corresponding to certificate_sha256_hash.',
    )
    generatedSplitApks: Optional[List[GeneratedSplitApk]] = Field(
        None,
        description='List of generated split APKs, signed with a key corresponding to certificate_sha256_hash.',
    )
    generatedStandaloneApks: Optional[List[GeneratedStandaloneApk]] = Field(
        None,
        description='List of generated standalone APKs, signed with a key corresponding to certificate_sha256_hash.',
    )
    generatedUniversalApk: Optional[GeneratedUniversalApk] = Field(
        None,
        description='Generated universal APK, signed with a key corresponding to certificate_sha256_hash. This field is not set if no universal APK was generated for this signing key.',
    )


class ListUsersResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token to pass to subsequent calls in order to retrieve subsequent results. This will not be set if there are no more results to return.',
    )
    users: Optional[List[User]] = Field(None, description='The resulting users.')


class ManagedProductTaxAndComplianceSettings(BaseModel):
    eeaWithdrawalRightType: Optional[EeaWithdrawalRightType] = Field(
        None,
        description='Digital content or service classification for products distributed to users in the European Economic Area (EEA). The withdrawal regime under EEA consumer laws depends on this classification. Refer to the [Help Center article](https://support.google.com/googleplay/android-developer/answer/10463498) for more information.',
    )
    taxRateInfoByRegionCode: Optional[Dict[str, RegionalTaxRateInfo]] = Field(
        None,
        description='A mapping from region code to tax rate details. The keys are region codes as defined by Unicode\'s "CLDR".',
    )


class MigrateBasePlanPricesRequest(BaseModel):
    regionalPriceMigrations: Optional[List[RegionalPriceMigrationConfig]] = Field(
        None, description='Required. The regional prices to update.'
    )
    regionsVersion: Optional[RegionsVersion] = Field(
        None,
        description='Required. The version of the available regions being used for the regional_price_migrations.',
    )


class OtherRegionsSubscriptionOfferPhaseConfig(BaseModel):
    absoluteDiscounts: Optional[OtherRegionsSubscriptionOfferPhasePrices] = Field(
        None,
        description='The absolute amount of money subtracted from the base plan price prorated over the phase duration that the user pays for this offer phase. For example, if the base plan price for this region is $12 for a period of 1 year, then a $1 absolute discount for a phase of a duration of 3 months would correspond to a price of $2. The resulting price may not be smaller than the minimum price allowed for any new locations Play may launch in.',
    )
    otherRegionsPrices: Optional[OtherRegionsSubscriptionOfferPhasePrices] = Field(
        None,
        description='The absolute price the user pays for this offer phase. The price must not be smaller than the minimum price allowed for any new locations Play may launch in.',
    )
    relativeDiscount: Optional[float] = Field(
        None,
        description='The fraction of the base plan price prorated over the phase duration that the user pays for this offer phase. For example, if the base plan price for this region is $12 for a period of 1 year, then a 50% discount for a phase of a duration of 3 months would correspond to a price of $1.50. The discount must be specified as a fraction strictly larger than 0 and strictly smaller than 1. The resulting price will be rounded to the nearest billable unit (e.g. cents for USD). The relative discount is considered invalid if the discounted price ends up being smaller than the minimum price allowed in any new locations Play may launch in.',
    )


class PartialRefund(BaseModel):
    refundId: Optional[str] = Field(
        None,
        description='Required. A unique id distinguishing this partial refund. If the refund is successful, subsequent refunds with the same id will fail. Must be unique across refunds for one individual transaction.',
    )
    refundPreTaxAmount: Optional[Price] = Field(
        None,
        description='Required. The pre-tax amount of the partial refund. Should be less than the remaining pre-tax amount of the transaction.',
    )


class RefundExternalTransactionRequest(BaseModel):
    fullRefund: Optional[FullRefund] = Field(None, description='A full-amount refund.')
    partialRefund: Optional[PartialRefund] = Field(
        None, description='A partial refund.'
    )
    refundTime: Optional[str] = Field(
        None, description='Required. The time that the transaction was refunded.'
    )


class ReviewReplyResult(BaseModel):
    lastEdited: Optional[Timestamp] = Field(
        None, description='The time at which the reply took effect.'
    )
    replyText: Optional[str] = Field(
        None, description='The reply text that was applied.'
    )


class ReviewsReplyResponse(BaseModel):
    result: Optional[ReviewReplyResult] = Field(
        None, description='The result of replying/updating a reply to review.'
    )


class Subscription(BaseModel):
    archived: Optional[bool] = Field(
        None,
        description='Output only. Whether this subscription is archived. Archived subscriptions are not available to any subscriber any longer, cannot be updated, and are not returned in list requests unless the show archived flag is passed in.',
    )
    basePlans: Optional[List[BasePlan]] = Field(
        None,
        description='The set of base plans for this subscription. Represents the prices and duration of the subscription if no other offers apply.',
    )
    listings: Optional[List[SubscriptionListing]] = Field(
        None,
        description='Required. List of localized listings for this subscription. Must contain at least an entry for the default language of the parent app.',
    )
    packageName: Optional[str] = Field(
        None, description='Immutable. Package name of the parent app.'
    )
    productId: Optional[str] = Field(
        None,
        description='Immutable. Unique product ID of the product. Unique within the parent app. Product IDs must be composed of lower-case letters (a-z), numbers (0-9), underscores (_) and dots (.). It must start with a lower-case letter or number, and be between 1 and 40 (inclusive) characters in length.',
    )
    taxAndComplianceSettings: Optional[SubscriptionTaxAndComplianceSettings] = Field(
        None, description='Details about taxes and legal compliance.'
    )


class SubscriptionOfferPhase(BaseModel):
    duration: Optional[str] = Field(
        None,
        description='Required. The duration of a single recurrence of this phase. Specified in ISO 8601 format.',
    )
    otherRegionsConfig: Optional[OtherRegionsSubscriptionOfferPhaseConfig] = Field(
        None,
        description='Pricing information for any new locations Play may launch in.',
    )
    recurrenceCount: Optional[int] = Field(
        None,
        description='Required. The number of times this phase repeats. If this offer phase is not free, each recurrence charges the user the price of this offer phase.',
    )
    regionalConfigs: Optional[List[RegionalSubscriptionOfferPhaseConfig]] = Field(
        None,
        description='Required. The region-specific configuration of this offer phase. This list must contain exactly one entry for each region for which the subscription offer has a regional config.',
    )


class SubscriptionOfferTargeting(BaseModel):
    acquisitionRule: Optional[AcquisitionTargetingRule] = Field(
        None, description='Offer targeting rule for new user acquisition.'
    )
    upgradeRule: Optional[UpgradeTargetingRule] = Field(
        None, description="Offer targeting rule for upgrading users' existing plans."
    )


class SubscriptionPurchaseLineItem(BaseModel):
    autoRenewingPlan: Optional[AutoRenewingPlan] = Field(
        None, description='The item is auto renewing.'
    )
    expiryTime: Optional[str] = Field(
        None,
        description='Time at which the subscription expired or will expire unless the access is extended (ex. renews).',
    )
    offerDetails: Optional[OfferDetails] = Field(
        None, description='The offer details for this item.'
    )
    prepaidPlan: Optional[PrepaidPlan] = Field(None, description='The item is prepaid.')
    productId: Optional[str] = Field(
        None, description="The purchased product ID (for example, 'monthly001')."
    )


class SubscriptionPurchaseV2(BaseModel):
    acknowledgementState: Optional[AcknowledgementState] = Field(
        None, description='The acknowledgement state of the subscription.'
    )
    canceledStateContext: Optional[CanceledStateContext] = Field(
        None,
        description='Additional context around canceled subscriptions. Only present if the subscription currently has subscription_state SUBSCRIPTION_STATE_CANCELED.',
    )
    externalAccountIdentifiers: Optional[ExternalAccountIdentifiers] = Field(
        None, description='User account identifier in the third-party service.'
    )
    kind: Optional[str] = Field(
        None,
        description='This kind represents a SubscriptionPurchaseV2 object in the androidpublisher service.',
    )
    latestOrderId: Optional[str] = Field(
        None,
        description='The order id of the latest order associated with the purchase of the subscription. For autoRenewing subscription, this is the order id of signup order if it is not renewed yet, or the last recurring order id (success, pending, or declined order). For prepaid subscription, this is the order id associated with the queried purchase token.',
    )
    lineItems: Optional[List[SubscriptionPurchaseLineItem]] = Field(
        None,
        description='Item-level info for a subscription purchase. The items in the same purchase should be either all with AutoRenewingPlan or all with PrepaidPlan.',
    )
    linkedPurchaseToken: Optional[str] = Field(
        None,
        description='The purchase token of the old subscription if this subscription is one of the following: * Re-signup of a canceled but non-lapsed subscription * Upgrade/downgrade from a previous subscription. * Convert from prepaid to auto renewing subscription. * Convert from an auto renewing subscription to prepaid. * Topup a prepaid subscription.',
    )
    pausedStateContext: Optional[PausedStateContext] = Field(
        None,
        description='Additional context around paused subscriptions. Only present if the subscription currently has subscription_state SUBSCRIPTION_STATE_PAUSED.',
    )
    regionCode: Optional[str] = Field(
        None,
        description='ISO 3166-1 alpha-2 billing country/region code of the user at the time the subscription was granted.',
    )
    startTime: Optional[str] = Field(
        None,
        description='Time at which the subscription was granted. Not set for pending subscriptions (subscription was created but awaiting payment during signup).',
    )
    subscribeWithGoogleInfo: Optional[SubscribeWithGoogleInfo] = Field(
        None,
        description="User profile associated with purchases made with 'Subscribe with Google'.",
    )
    subscriptionState: Optional[SubscriptionState] = Field(
        None, description='The current state of the subscription.'
    )
    testPurchase: Optional[TestPurchase] = Field(
        None,
        description='Only present if this subscription purchase is a test purchase.',
    )


class SystemApksListResponse(BaseModel):
    variants: Optional[List[Variant]] = Field(
        None, description='All system APK variants created.'
    )


class Track(BaseModel):
    releases: Optional[List[TrackRelease]] = Field(
        None,
        description='In a read request, represents all active releases in the track. In an update request, represents desired changes.',
    )
    track: Optional[str] = Field(
        None,
        description='Identifier of the track. Form factor tracks have a special prefix as an identifier, for example `wear:production`, `automotive:production`. [More on track name](https://developers.google.com/android-publisher/tracks#ff-track-name)',
    )


class TrackCountryAvailability(BaseModel):
    countries: Optional[List[TrackTargetedCountry]] = Field(
        None,
        description='A list of one or more countries where artifacts in this track are available. This list includes all countries that are targeted by the track, even if only specific carriers are targeted in that country.',
    )
    restOfWorld: Optional[bool] = Field(
        None,
        description='Whether artifacts in this track are available to "rest of the world" countries.',
    )
    syncWithProduction: Optional[bool] = Field(
        None,
        description='Whether this track\'s availability is synced with the default production track. See https://support.google.com/googleplay/android-developer/answer/7550024 for more information on syncing country availability with production. Note that if this is true, the returned "countries" and "rest_of_world" fields will reflect the values for the default production track.',
    )


class TracksListResponse(BaseModel):
    kind: Optional[str] = Field(
        None,
        description='The kind of this response ("androidpublisher#tracksListResponse").',
    )
    tracks: Optional[List[Track]] = Field(None, description='All tracks.')


class ApksAddExternallyHostedRequest(BaseModel):
    externallyHostedApk: Optional[ExternallyHostedApk] = Field(
        None,
        description='The definition of the externally-hosted APK and where it is located.',
    )


class ApksAddExternallyHostedResponse(BaseModel):
    externallyHostedApk: Optional[ExternallyHostedApk] = Field(
        None,
        description='The definition of the externally-hosted APK and where it is located.',
    )


class Comment(BaseModel):
    developerComment: Optional[DeveloperComment] = Field(
        None, description='A comment from a developer.'
    )
    userComment: Optional[UserComment] = Field(
        None, description='A comment from a user.'
    )


class ConvertRegionPricesResponse(BaseModel):
    convertedOtherRegionsPrice: Optional[ConvertedOtherRegionsPrice] = Field(
        None,
        description="Converted other regions prices in USD and EUR, to use for countries where Play doesn't support a country's local currency.",
    )
    convertedRegionPrices: Optional[Dict[str, ConvertedRegionPrice]] = Field(
        None, description='Map from region code to converted region price.'
    )


class DeviceGroup(BaseModel):
    deviceSelectors: Optional[List[DeviceSelector]] = Field(
        None,
        description='Device selectors for this group. A device matching any of the selectors is included in this group.',
    )
    name: Optional[str] = Field(None, description='The name of the group.')


class DeviceTierConfig(BaseModel):
    deviceGroups: Optional[List[DeviceGroup]] = Field(
        None, description='Definition of device groups for the app.'
    )
    deviceTierConfigId: Optional[str] = Field(
        None, description='Output only. The device tier config ID.'
    )
    deviceTierSet: Optional[DeviceTierSet] = Field(
        None, description='Definition of the set of device tiers for the app.'
    )
    userCountrySets: Optional[List[UserCountrySet]] = Field(
        None, description='Definition of user country sets for the app.'
    )


class GeneratedApksListResponse(BaseModel):
    generatedApks: Optional[List[GeneratedApksPerSigningKey]] = Field(
        None, description='All generated APKs, grouped by the APK signing key.'
    )


class InAppProduct(BaseModel):
    defaultLanguage: Optional[str] = Field(
        None,
        description='Default language of the localized data, as defined by BCP-47. e.g. "en-US".',
    )
    defaultPrice: Optional[Price] = Field(
        None,
        description="Default price. Cannot be zero, as in-app products are never free. Always in the developer's Checkout merchant currency.",
    )
    gracePeriod: Optional[str] = Field(
        None,
        description='Grace period of the subscription, specified in ISO 8601 format. Allows developers to give their subscribers a grace period when the payment for the new recurrence period is declined. Acceptable values are P0D (zero days), P3D (three days), P7D (seven days), P14D (14 days), and P30D (30 days).',
    )
    listings: Optional[Dict[str, InAppProductListing]] = Field(
        None,
        description='List of localized title and description data. Map key is the language of the localized data, as defined by BCP-47, e.g. "en-US".',
    )
    managedProductTaxesAndComplianceSettings: Optional[
        ManagedProductTaxAndComplianceSettings
    ] = Field(
        None,
        description='Details about taxes and legal compliance. Only applicable to managed products.',
    )
    packageName: Optional[str] = Field(
        None, description='Package name of the parent app.'
    )
    prices: Optional[Dict[str, Price]] = Field(
        None,
        description='Prices per buyer region. None of these can be zero, as in-app products are never free. Map key is region code, as defined by ISO 3166-2.',
    )
    purchaseType: Optional[PurchaseType] = Field(
        None, description='The type of the product, e.g. a recurring subscription.'
    )
    sku: Optional[str] = Field(
        None,
        description='Stock-keeping-unit (SKU) of the product, unique within an app.',
    )
    status: Optional[Status] = Field(
        None, description="The status of the product, e.g. whether it's active."
    )
    subscriptionPeriod: Optional[str] = Field(
        None,
        description='Subscription period, specified in ISO 8601 format. Acceptable values are P1W (one week), P1M (one month), P3M (three months), P6M (six months), and P1Y (one year).',
    )
    subscriptionTaxesAndComplianceSettings: Optional[
        SubscriptionTaxAndComplianceSettings
    ] = Field(
        None,
        description='Details about taxes and legal compliance. Only applicable to subscription products.',
    )
    trialPeriod: Optional[str] = Field(
        None,
        description='Trial period, specified in ISO 8601 format. Acceptable values are anything between P7D (seven days) and P999D (999 days).',
    )


class InappproductsListResponse(BaseModel):
    inappproduct: Optional[List[InAppProduct]] = Field(
        None, description='All in-app products.'
    )
    kind: Optional[str] = Field(
        None,
        description='The kind of this response ("androidpublisher#inappproductsListResponse").',
    )
    pageInfo: Optional[PageInfo] = Field(None, description='Deprecated and unset.')
    tokenPagination: Optional[TokenPagination] = Field(
        None,
        description='Pagination token, to handle a number of products that is over one page.',
    )


class ListDeviceTierConfigsResponse(BaseModel):
    deviceTierConfigs: Optional[List[DeviceTierConfig]] = Field(
        None, description='Device tier configs created by the developer.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class ListSubscriptionsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )
    subscriptions: Optional[List[Subscription]] = Field(
        None, description='The subscriptions from the specified app.'
    )


class Review(BaseModel):
    authorName: Optional[str] = Field(
        None, description='The name of the user who wrote the review.'
    )
    comments: Optional[List[Comment]] = Field(
        None, description='A repeated field containing comments for the review.'
    )
    reviewId: Optional[str] = Field(
        None, description='Unique identifier for this review.'
    )


class ReviewsListResponse(BaseModel):
    pageInfo: Optional[PageInfo] = Field(
        None, description='Information about the current page.'
    )
    reviews: Optional[List[Review]] = Field(None, description='List of reviews.')
    tokenPagination: Optional[TokenPagination] = Field(
        None,
        description='Pagination token, to handle a number of products that is over one page.',
    )


class SubscriptionOffer(BaseModel):
    basePlanId: Optional[str] = Field(
        None,
        description='Required. Immutable. The ID of the base plan to which this offer is an extension.',
    )
    offerId: Optional[str] = Field(
        None,
        description='Required. Immutable. Unique ID of this subscription offer. Must be unique within the base plan.',
    )
    offerTags: Optional[List[OfferTag]] = Field(
        None,
        description='List of up to 20 custom tags specified for this offer, and returned to the app through the billing library.',
    )
    otherRegionsConfig: Optional[OtherRegionsSubscriptionOfferConfig] = Field(
        None,
        description='The configuration for any new locations Play may launch in the future.',
    )
    packageName: Optional[str] = Field(
        None,
        description='Required. Immutable. The package name of the app the parent subscription belongs to.',
    )
    phases: Optional[List[SubscriptionOfferPhase]] = Field(
        None,
        description='Required. The phases of this subscription offer. Must contain at least one entry, and may contain at most five. Users will always receive all these phases in the specified order. Phases may not be added, removed, or reordered after initial creation.',
    )
    productId: Optional[str] = Field(
        None,
        description='Required. Immutable. The ID of the parent subscription this offer belongs to.',
    )
    regionalConfigs: Optional[List[RegionalSubscriptionOfferConfig]] = Field(
        None,
        description='Required. The region-specific configuration of this offer. Must contain at least one entry.',
    )
    state: Optional[State] = Field(
        None,
        description='Output only. The current state of this offer. Can be changed using Activate and Deactivate actions. NB: the base plan state supersedes this state, so an active offer may not be available if the base plan is not active.',
    )
    targeting: Optional[SubscriptionOfferTargeting] = Field(
        None,
        description='The requirements that users need to fulfil to be eligible for this offer. Represents the requirements that Play will evaluate to decide whether an offer should be returned. Developers may further filter these offers themselves.',
    )


class ListSubscriptionOffersResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )
    subscriptionOffers: Optional[List[SubscriptionOffer]] = Field(
        None, description='The subscription offers from the specified subscription.'
    )
